/**
 * Commercial Report Generator
 *
 * Generates professional HTML reports for client delivery.
 * NO PDF dependencies - outputs HTML that can be printed to PDF.
 */

import type { InspectionResultV1, Finding, Opportunity } from '@argus/schema';

export interface ReportOptions {
  language?: 'es' | 'en' | 'nl';
  companyName?: string;
  assessmentDate?: string;
  assessorName?: string;
  includeTechnicalDetails?: boolean;
}

const TRANSLATIONS = {
  es: {
    title: 'Informe de Seguridad Web',
    subtitle: 'Análisis de Postura de Seguridad',
    executiveSummary: 'Resumen Ejecutivo',
    findings: 'Hallazgos',
    opportunities: 'Oportunidades de Mejora',
    technicalDetails: 'Detalles Técnicos',
    recommendations: 'Recomendaciones',
    nextSteps: 'Próximos Pasos',
    assessedTarget: 'Objetivo evaluado',
    assessmentDate: 'Fecha de evaluación',
    findingsCount: 'Hallazgos identificados',
    severity: 'Severidad',
    confidence: 'Confianza',
    high: 'ALTA',
    medium: 'MEDIA',
    low: 'BAJA',
    verified: 'VERIFICADO',
    supported: 'CONFIRMADO',
    inferred: 'INFERIDO',
    remediation: 'Remediación',
    businessValue: 'Valor de Negocio',
    technicalComplexity: 'Complejidad Técnica',
    estimatedEffort: 'Esfuerzo Estimado',
    contactInfo: 'Para implementar estas mejoras, contacte con',
    poweredBy: 'Generado por ARGUS',
    evidenceBasedAnalysis: 'Análisis basado en evidencia verificable'
  },
  en: {
    title: 'Web Security Report',
    subtitle: 'Security Posture Analysis',
    executiveSummary: 'Executive Summary',
    findings: 'Findings',
    opportunities: 'Improvement Opportunities',
    technicalDetails: 'Technical Details',
    recommendations: 'Recommendations',
    nextSteps: 'Next Steps',
    assessedTarget: 'Assessed target',
    assessmentDate: 'Assessment date',
    findingsCount: 'Findings identified',
    severity: 'Severity',
    confidence: 'Confidence',
    high: 'HIGH',
    medium: 'MEDIUM',
    low: 'LOW',
    verified: 'VERIFIED',
    supported: 'SUPPORTED',
    inferred: 'INFERRED',
    remediation: 'Remediation',
    businessValue: 'Business Value',
    technicalComplexity: 'Technical Complexity',
    estimatedEffort: 'Estimated Effort',
    contactInfo: 'To implement these improvements, contact',
    poweredBy: 'Generated by ARGUS',
    evidenceBasedAnalysis: 'Analysis based on verifiable evidence'
  },
  nl: {
    title: 'Website Beveiligingsrapport',
    subtitle: 'Beveiligingsanalyse',
    executiveSummary: 'Managementsamenvatting',
    findings: 'Bevindingen',
    opportunities: 'Verbeterkansen',
    technicalDetails: 'Technische Details',
    recommendations: 'Aanbevelingen',
    nextSteps: 'Volgende Stappen',
    assessedTarget: 'Beoordeeld doel',
    assessmentDate: 'Beoordelingsdatum',
    findingsCount: 'Gevonden problemen',
    severity: 'Ernst',
    confidence: 'Vertrouwen',
    high: 'HOOG',
    medium: 'GEMIDDELD',
    low: 'LAAG',
    verified: 'GEVERIFIEERD',
    supported: 'ONDERSTEUND',
    inferred: 'AFGELEID',
    remediation: 'Oplossing',
    businessValue: 'Bedrijfswaarde',
    technicalComplexity: 'Technische Complexiteit',
    estimatedEffort: 'Geschatte Inspanning',
    contactInfo: 'Voor implementatie van deze verbeteringen, neem contact op met',
    poweredBy: 'Gegenereerd door ARGUS',
    evidenceBasedAnalysis: 'Analyse gebaseerd op verifieerbaar bewijs'
  }
};

export function generateCommercialReport(
  inspection: InspectionResultV1,
  options: ReportOptions = {}
): string {
  const lang = options.language || 'es';
  const t = TRANSLATIONS[lang];
  const date = options.assessmentDate || new Date().toLocaleDateString(lang === 'es' ? 'es-ES' : 'en-US');

  const severityCounts = {
    CRITICAL: inspection.findings.filter(f => f.severity === 'CRITICAL').length,
    HIGH: inspection.findings.filter(f => f.severity === 'HIGH').length,
    MEDIUM: inspection.findings.filter(f => f.severity === 'MEDIUM').length,
    LOW: inspection.findings.filter(f => f.severity === 'LOW').length
  };

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t.title} - ${inspection.target.hostname}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    @page {
      margin: 2cm;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
      line-height: 1.6;
      color: #2c3e50;
      background: #ffffff;
      font-size: 11pt;
    }

    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      border-bottom: 3px solid #3498db;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }

    .header h1 {
      font-size: 28pt;
      color: #2c3e50;
      margin-bottom: 5px;
    }

    .header .subtitle {
      font-size: 14pt;
      color: #7f8c8d;
    }

    .company-name {
      font-size: 16pt;
      color: #3498db;
      font-weight: bold;
      margin-top: 10px;
    }

    .meta-info {
      background: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 25px;
    }

    .meta-info p {
      margin: 5px 0;
    }

    .meta-info strong {
      color: #2c3e50;
    }

    .section {
      margin-bottom: 30px;
      break-inside: avoid;
    }

    .section-title {
      font-size: 18pt;
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 8px;
      margin-bottom: 15px;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }

    .stat-card {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      border-left: 4px solid #3498db;
    }

    .stat-label {
      font-size: 10pt;
      color: #7f8c8d;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .stat-value {
      font-size: 24pt;
      font-weight: bold;
      color: #2c3e50;
      margin-top: 5px;
    }

    .finding {
      background: #fff;
      border: 1px solid #ddd;
      border-radius: 5px;
      padding: 15px;
      margin-bottom: 15px;
      break-inside: avoid;
    }

    .finding-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
    }

    .finding-title {
      font-size: 13pt;
      font-weight: bold;
      color: #2c3e50;
    }

    .severity-badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 3px;
      font-size: 9pt;
      font-weight: bold;
      text-transform: uppercase;
    }

    .severity-critical {
      background: #e74c3c;
      color: white;
    }

    .severity-high {
      background: #e67e22;
      color: white;
    }

    .severity-medium {
      background: #f39c12;
      color: white;
    }

    .severity-low {
      background: #95a5a6;
      color: white;
    }

    .finding-description {
      color: #555;
      margin-bottom: 10px;
    }

    .finding-remediation {
      background: #e8f5e9;
      border-left: 3px solid #4caf50;
      padding: 10px;
      margin-top: 10px;
      font-size: 10pt;
    }

    .finding-remediation strong {
      color: #2e7d32;
    }

    .opportunity {
      background: #e3f2fd;
      border-left: 4px solid #2196f3;
      padding: 15px;
      margin-bottom: 15px;
      break-inside: avoid;
    }

    .opportunity-title {
      font-size: 13pt;
      font-weight: bold;
      color: #1565c0;
      margin-bottom: 8px;
    }

    .opportunity-value {
      color: #424242;
      margin-bottom: 8px;
      font-size: 10pt;
    }

    .complexity-badge {
      display: inline-block;
      padding: 3px 10px;
      background: #fff;
      border: 1px solid #2196f3;
      border-radius: 3px;
      font-size: 9pt;
      color: #1565c0;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #ecf0f1;
      text-align: center;
      color: #7f8c8d;
      font-size: 9pt;
    }

    .contact-box {
      background: #fff3cd;
      border: 1px solid #ffc107;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
      text-align: center;
    }

    .contact-box strong {
      color: #856404;
    }

    @media print {
      .container {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${t.title}</h1>
      <div class="subtitle">${t.subtitle}</div>
      ${options.companyName ? `<div class="company-name">${options.companyName}</div>` : ''}
    </div>

    <div class="meta-info">
      <p><strong>${t.assessedTarget}:</strong> ${inspection.target.hostname}</p>
      <p><strong>${t.assessmentDate}:</strong> ${date}</p>
      <p><strong>${t.findingsCount}:</strong> ${inspection.findings.length}</p>
      ${options.assessorName ? `<p><strong>Evaluado por:</strong> ${options.assessorName}</p>` : ''}
    </div>

    <div class="section">
      <h2 class="section-title">${t.executiveSummary}</h2>
      <div class="stats-grid">
        ${severityCounts.CRITICAL > 0 ? `
        <div class="stat-card">
          <div class="stat-label">Críticos</div>
          <div class="stat-value" style="color: #e74c3c;">${severityCounts.CRITICAL}</div>
        </div>` : ''}
        ${severityCounts.HIGH > 0 ? `
        <div class="stat-card">
          <div class="stat-label">Alta Prioridad</div>
          <div class="stat-value" style="color: #e67e22;">${severityCounts.HIGH}</div>
        </div>` : ''}
        ${severityCounts.MEDIUM > 0 ? `
        <div class="stat-card">
          <div class="stat-label">Media Prioridad</div>
          <div class="stat-value" style="color: #f39c12;">${severityCounts.MEDIUM}</div>
        </div>` : ''}
        ${severityCounts.LOW > 0 ? `
        <div class="stat-card">
          <div class="stat-label">Baja Prioridad</div>
          <div class="stat-value" style="color: #95a5a6;">${severityCounts.LOW}</div>
        </div>` : ''}
      </div>
    </div>

    ${inspection.findings.length > 0 ? `
    <div class="section">
      <h2 class="section-title">${t.findings}</h2>
      ${inspection.findings.map(finding => `
        <div class="finding">
          <div class="finding-header">
            <div class="finding-title">${finding.title}</div>
            <span class="severity-badge severity-${finding.severity.toLowerCase()}">${finding.severity}</span>
          </div>
          <div class="finding-description">${finding.description}</div>
          ${options.includeTechnicalDetails && finding.technicalExplanation ? `
            <div style="font-size: 10pt; color: #666; margin-top: 8px;">
              <strong>Detalle técnico:</strong> ${finding.technicalExplanation}
            </div>
          ` : ''}
          <div class="finding-remediation">
            <strong>${t.remediation}:</strong> ${finding.remediation}
          </div>
        </div>
      `).join('')}
    </div>
    ` : ''}

    ${inspection.opportunities.length > 0 ? `
    <div class="section">
      <h2 class="section-title">${t.opportunities}</h2>
      ${inspection.opportunities.map(opp => `
        <div class="opportunity">
          <div class="opportunity-title">${opp.title}</div>
          <div class="opportunity-value"><strong>${t.businessValue}:</strong> ${opp.businessSignificance}</div>
          <div class="opportunity-value"><strong>${t.technicalComplexity}:</strong> <span class="complexity-badge">${opp.estimatedComplexity}</span></div>
        </div>
      `).join('')}
    </div>
    ` : ''}

    ${options.assessorName ? `
    <div class="contact-box">
      <p><strong>${t.contactInfo} ${options.assessorName}</strong></p>
    </div>
    ` : ''}

    <div class="footer">
      <p>${t.poweredBy} • ${t.evidenceBasedAnalysis}</p>
      <p style="margin-top: 5px;">Informe generado el ${new Date().toLocaleString(lang === 'es' ? 'es-ES' : 'en-US')}</p>
    </div>
  </div>
</body>
</html>`;
}
